FROM python:3.7
WORKDIR "/home"

RUN pip install --upgrade pip

# Install dependencies:
COPY requirements.txt ./
RUN pip install wheel setuptools
RUN pip install -r requirements.txt

# Set up jupyter notebooks
RUN pip install jupyter
RUN python -m ipykernel install --name micdrop_subscription_funnel

# Expose Airflow Port
EXPOSE 8080

# Expose Jupyter Port
EXPOSE 8888

# Copy repo into image
ADD . /home

# Install package
RUN pip install -e /home

ENTRYPOINT ["python micdrop/app.py"]